spring:
  application:
    name: pal

  profiles:
    active:
      - '@spring.profiles.active@'

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

server:
  port: ${SERVER_PORT:9090}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  info:
    title: API PAL
    version: v1.0.0
    description: Documentacion de la API del servicio PAL
    terms-of-service: https://example.com/terminos
    contact:
      name: Equipo de Desarrollo
      email: desarrollo@example.com
    license:
      name: Apache 2.0
      url: https://springdoc.org/license.html
